const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');let W,H,DPR;function resize(){DPR=devicePixelRatio||1;W=innerWidth;H=innerHeight;canvas.width=W*DPR;canvas.height=H*DPR;ctx.setTransform(DPR,0,0,DPR,0,0)}addEventListener('resize',resize);resize();
const keys={};const map={KeyA:'left',KeyD:'right',KeyW:'jump',KeyJ:'punch',KeyK:'kick',KeyL:'blast',KeyI:'ult',Space:'dash'};addEventListener('keydown',e=>{let k=map[e.code];if(k){keys[k]=true;e.preventDefault();}});addEventListener('keyup',e=>{let k=map[e.code];if(k)keys[k]=false;});document.querySelectorAll('[data-k]').forEach(b=>['pointerdown','pointerup','pointercancel'].forEach(ev=>b.addEventListener(ev,e=>{keys[b.dataset.k]=ev==='pointerdown';e.preventDefault()})));
let ground=0,time=0,shake=0,particles=[],projectiles=[],round=1,gameOver=false;function msg(s){let m=document.getElementById('message');m.textContent=s;m.style.opacity=1;setTimeout(()=>m.style.opacity=0,800)}
class Fighter{constructor(name,x,face,color,ai=false){Object.assign(this,{name,x,y:0,face,color,ai,vx:0,vy:0,hp:100,ki:100,state:'idle',timer:0,cool:0,combo:0,lastHit:0,hitDone:false,stun:0,flash:0,trail:[],dead:false});} attack(type){if(this.dead||this.stun>0||this.state!=='idle')return;let cost=type==='ult'?100:type==='blast'?18:type==='dash'?10:0;if(this.ki<cost)return;this.ki-=cost;this.state=type;this.timer=0;this.hitDone=false;if(type==='punch')this.combo=(this.combo+1)%2; if(type==='dash')this.vx=this.face*850; if(type==='ult')msg('NOVA BURST!');}
 update(dt,opp){this.timer+=dt;this.cool=Math.max(0,this.cool-dt);this.stun=Math.max(0,this.stun-dt);this.flash=Math.max(0,this.flash-dt);this.trail.unshift({x:this.x,y:this.y,a:.35});if(this.trail.length>8)this.trail.pop();this.trail.forEach(t=>t.a-=dt);if(!this.ai&&!this.dead&&this.stun<=0&&this.state==='idle'){if(keys.left)this.vx=-340;if(keys.right)this.vx=340;if(keys.jump&&this.y===ground){this.vy=-680}if(keys.punch)this.attack('punch');if(keys.kick)this.attack('kick');if(keys.blast)this.attack('blast');if(keys.dash)this.attack('dash');if(keys.ult)this.attack('ult');}
 if(this.ai&&!this.dead&&this.stun<=0&&this.state==='idle'){let d=opp.x-this.x;if(Math.abs(d)>180)this.vx=Math.sign(d)*220;else if(Math.random()<.035)this.attack(Math.random()<.55?'punch':Math.random()<.75?'kick':'blast');if(Math.abs(d)>260&&Math.random()<.01)this.attack('dash');}
 this.vy+=1700*dt;this.x+=this.vx*dt;this.y+=this.vy*dt;this.vx*=Math.pow(.0008,dt);if(this.y>=ground){this.y=ground;this.vy=0}this.x=Math.max(60,Math.min(W-60,this.x));if(this.state!=='idle')this.act(dt,opp);else this.ki=Math.min(100,this.ki+5*dt);}
 act(dt,opp){let dur={punch:.42,kick:.52,blast:.58,dash:.32,ult:1.05}[this.state]||.4,p=this.timer/dur;if((this.state==='punch'||this.state==='kick'||this.state==='dash')&&!this.hitDone&&p>.32){this.hitDone=true;let range=this.state==='kick'?145:this.state==='dash'?190:120;if(Math.abs(opp.x-this.x)<range&&Math.abs(opp.y-this.y)<110)this.hit(opp,this.state==='kick'?10:this.state==='dash'?12:7);}
 if(this.state==='blast'&&!this.hitDone&&p>.48){this.hitDone=true;projectiles.push({x:this.x+this.face*55,y:this.y-105,vx:this.face*720,r:13,owner:this,life:1.8,damage:13});}
 if(this.state==='ult'&&!this.hitDone&&p>.72){this.hitDone=true;for(let i=0;i<36;i++){let a=i/36*Math.PI*2;projectiles.push({x:this.x,y:this.y-95,vx:Math.cos(a)*520,vy:Math.sin(a)*520,r:9,owner:this,life:.75,damage:8});}}
 if(p>=1){this.state='idle';this.timer=0;this.vx=0;}}
 hit(o,dmg){o.hp=Math.max(0,o.hp-dmg);o.stun=.18;o.state='hit';o.timer=0;o.vx=this.face*420;o.vy=-150;o.flash=.12;shake=10;this.ki=Math.min(100,this.ki+9);for(let i=0;i<16;i++)particles.push({x:o.x,y:o.y-95,vx:(Math.random()-.5)*500,vy:(Math.random()-.5)*500,life:.35,size:3+Math.random()*5});if(o.hp<=0){o.dead=true;o.vx=this.face*600;o.vy=-450;msg(this.name+' WINS!');setTimeout(reset,1600)}}
 pose(){let p=this.timer, n=this.state==='punch'?(this.combo?'punch2':'punch1'):this.state;let f=A[n]||A.idle;return f(n==='idle'||n==='walk'?time:p);}
 draw(){let p=this.pose(),x=this.x,y=this.y,dir=this.face;ctx.save();ctx.translate(x,y);ctx.scale(dir,1);ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle=this.flash>0?'#fff':this.color;ctx.shadowColor=this.color;ctx.shadowBlur=12;ctx.lineWidth=11;
 // torso + articulated limbs
 let hip=[0,-62],should=[p.body*18,-125],head=[p.head*9,-162];ctx.beginPath();ctx.moveTo(...hip);ctx.lineTo(...should);ctx.stroke();function limb(root,a,b,c){let l1=43,l2=42,k=[root[0]+Math.sin(a)*l1,root[1]+Math.cos(a)*l1],e=[k[0]+Math.sin(a+b)*l2,k[1]+Math.cos(a+b)*l2];ctx.beginPath();ctx.moveTo(...root);ctx.lineTo(...k);ctx.lineTo(...e);ctx.stroke();return e}
 let rearArm=limb(should,p.shoulder-.75,p.elbow,0),frontArm=limb(should,p.shoulder+.55,p.elbow,0);let rearHip=[hip[0]-5,hip[1]],frontHip=[hip[0]+5,hip[1]];limb(rearHip,p.hip-.45,p.backLeg,0);limb(frontHip,p.hip+.5,p.frontLeg,0);ctx.fillStyle=this.flash>0?'#fff':this.color;ctx.shadowBlur=14;ctx.beginPath();ctx.arc(...head,23,0,Math.PI*2);ctx.fill();ctx.fillStyle='rgba(255,255,255,.18)';ctx.beginPath();ctx.arc(head[0]-7,head[1]-8,8,0,Math.PI*2);ctx.fill();ctx.restore();}
}
let p1,p2;function reset(){gameOver=false;ground=H-150;p1=new Fighter('NOVA',W*.32,1,'#e8f3ff');p2=new Fighter('VEX',W*.68,-1,'#ffd35c',true);msg('FIGHT!')}reset();
function update(dt){time+=dt;ground=H-150;p1.update(dt,p2);p2.update(dt,p1);for(let pr of projectiles){pr.x+=pr.vx*dt;pr.y+=(pr.vy||0)*dt;pr.life-=dt;if(pr.owner!==p1&&Math.hypot(pr.x-p1.x,pr.y-(p1.y-95))<48){pr.life=0;pr.owner.hit(p1,pr.damage)}if(pr.owner!==p2&&Math.hypot(pr.x-p2.x,pr.y-(p2.y-95))<48){pr.life=0;pr.owner.hit(p2,pr.damage)}}projectiles=projectiles.filter(q=>q.life>0&&q.x>-100&&q.x<W+100);particles.forEach(q=>{q.x+=q.vx*dt;q.y+=q.vy*dt;q.life-=dt});particles=particles.filter(q=>q.life>0);shake=Math.max(0,shake-45*dt);document.getElementById('hp1').style.width=p1.hp+'%';document.getElementById('hp2').style.width=p2.hp+'%';document.getElementById('ki1').style.width=p1.ki+'%';document.getElementById('ki2').style.width=p2.ki+'%';}
function draw(){let g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#10172e');g.addColorStop(.62,'#30223b');g.addColorStop(1,'#111427');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.save();ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);ctx.fillStyle='#1b1e36';for(let i=0;i<W;i+=90){let h=90+Math.sin(i*.17)*100;ctx.beginPath();ctx.moveTo(i,H-150);ctx.lineTo(i+45,H-150-h);ctx.lineTo(i+90,H-150);ctx.fill()}ctx.fillStyle='#252840';ctx.fillRect(0,H-150,W,150);ctx.strokeStyle='rgba(255,180,100,.14)';for(let i=0;i<W;i+=110){ctx.beginPath();ctx.moveTo(i,H-125);ctx.lineTo(i+70,H-135);ctx.stroke()}
 for(const f of [p1,p2])for(const t of f.trail.slice(2)){if(t.a>0){ctx.globalAlpha=Math.max(0,t.a);ctx.fillStyle=f.color;ctx.beginPath();ctx.arc(t.x,t.y-100,12,0,7);ctx.fill()}}ctx.globalAlpha=1;p1.draw();p2.draw();for(const pr of projectiles){ctx.shadowColor='#ffcf63';ctx.shadowBlur=25;ctx.fillStyle='#ffe08a';ctx.beginPath();ctx.arc(pr.x,pr.y,pr.r,0,7);ctx.fill()}ctx.shadowBlur=0;for(const q of particles){ctx.globalAlpha=q.life/.35;ctx.fillStyle='#fff3a5';ctx.fillRect(q.x,q.y,q.size,q.size)}ctx.globalAlpha=1;ctx.restore();}
let last=performance.now();function loop(now){let dt=Math.min(.033,(now-last)/1000);last=now;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);if(window.PokiSDK){PokiSDK.init().then(()=>PokiSDK.gameLoadingFinished()).catch(()=>{});}addEventListener('blur',()=>{if(window.PokiSDK)PokiSDK.gameplayStop()});canvas.addEventListener('pointerdown',()=>{if(window.PokiSDK)PokiSDK.gameplayStart()},{once:true});