const C=document.getElementById('game'),X=C.getContext('2d');
let W=innerWidth,H=innerHeight,dpr=Math.min(devicePixelRatio||1,2);function resize(){W=innerWidth;H=innerHeight;C.width=W*dpr;C.height=H*dpr;X.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
const keys={};addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=1;if([' ','arrowleft','arrowright','arrowup'].includes(e.key.toLowerCase()))e.preventDefault()});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=0);
const touch={};function bindTouch(el,action){el.addEventListener('pointerdown',e=>{e.preventDefault();touch[action]=1});['pointerup','pointercancel','pointerleave'].forEach(t=>el.addEventListener(t,e=>{e.preventDefault();touch[action]=0}))}
const buttons=[['left','◀'],['right','▶'],['jump','▲'],['punch','P'],['kick','K'],['blast','E'],['dash','◆']];let ui=[];function makeUI(){ui.forEach(b=>b.remove());ui=[];if(W>800)return;buttons.forEach(([a,t],i)=>{let b=document.createElement('button');b.textContent=t;b.style.cssText=`position:fixed;bottom:${18+(i<3?0:72)}px;${i<3?`left:${18+i*66}px`:`right:${18+(i-3)*66}px`};width:56px;height:56px;border-radius:50%;border:1px solid #6df;background:#10162ecc;color:#fff;font-weight:bold;font-size:20px;touch-action:none`;document.body.appendChild(b);bindTouch(b,a);ui.push(b)})}makeUI();addEventListener('resize',makeUI);
function pokiInit(){if(window.PokiSDK){PokiSDK.init().then(()=>PokiSDK.gameLoadingFinished()).catch(()=>{});}}pokiInit();
function ad(){if(window.PokiSDK&&PokiSDK.commercialBreak){PokiSDK.gameplayStop();PokiSDK.commercialBreak().then(()=>PokiSDK.gameplayStart()).catch(()=>PokiSDK.gameplayStart())}}
function reward(){if(window.PokiSDK&&PokiSDK.rewardedBreak){PokiSDK.gameplayStop();PokiSDK.rewardedBreak({size:'small'}).then(ok=>{if(ok)player.hp=Math.min(player.maxhp,player.hp+90);PokiSDK.gameplayStart()})}}
let state='menu',time=0,shake=0,round=1,score=0;
const world={floor:()=>H*.78,left:70,right:W-70};
function fighter(x,flip,color,name){return{ x,y:world.floor()-78,vx:0,vy:0,flip,color,name,hp:300,maxhp:300,en:0,maxen:100,ground:true,action:'idle',frame:0,cool:0,hit:0,stun:0,combo:0,comboT:0,flash:0}}
let player=fighter(W*.32,false,'#e9f6ff','NOVA'),enemy=fighter(W*.68,true,'#f6cf5b','VEX');
function reset(){player=fighter(W*.32,false,'#e9f6ff','NOVA');enemy=fighter(W*.68,true,'#f6cf5b','VEX');round++;state='fight';if(window.PokiSDK)PokiSDK.gameplayStart()}
function input(action){return !!(keys[action]||touch[action])}
function attack(f,type,target){if(f.cool>0||f.stun>0)return;f.frame=0;f.action=type;f.cool=type==='punch'?18:type==='kick'?24:type==='blast'?42:30;if(type==='blast'){f.en=Math.max(0,f.en-28)}
}
function updateF(f,t,other,isPlayer){if(f.stun>0){f.stun--;f.action='stun';f.vx*=.88}else{let l=isPlayer?input('a')||input('left'):false,r=isPlayer?input('d')||input('right'):false;if(isPlayer){if(l)f.vx-=.75;if(r)f.vx+=.75;if(input('w')||input('jump')){if(f.ground){f.vy=-11;f.ground=false}}if(input(' ')||input('dash')){if(f.cool<=0){f.vx+=(f.flip?-1:1)*7;f.cool=24;f.action='dash'}}if(input('j')||input('punch'))attack(f,'punch',other);if(input('k')||input('kick'))attack(f,'kick',other);if((input('l')||input('blast'))&&f.en>=28)attack(f,'blast',other)}else{let dx=other.x-f.x;if(Math.abs(dx)>110)f.vx+=Math.sign(dx)*.35;else if(f.cool<=0){if(Math.random()<.55)attack(f,Math.random()<.55?'punch':'kick',other);else if(f.en>=28)attack(f,'blast',other)}if(Math.abs(dx)<95&&Math.random()<.02&&f.ground){f.vy=-10;f.ground=false}}
if(f.ground)f.vx*=.84;else f.vx*=.97;f.vy+=.55;f.x+=f.vx;f.y+=f.vy;if(f.y>=world.floor()-78){f.y=world.floor()-78;f.vy=0;f.ground=true}f.x=Math.max(world.left,Math.min(world.right,f.x));
}
f.cool=Math.max(0,f.cool-1);f.frame++;f.comboT=Math.max(0,f.comboT-1);f.flash=Math.max(0,f.flash-1);if(f.comboT===0)f.combo=0;
if(f.action==='punch'&&f.frame===7)doHit(f,other,24,58);if(f.action==='kick'&&f.frame===9)doHit(f,other,32,74);if(f.action==='blast'&&f.frame===14)projectile(f,other);if(f.frame>28)f.action='idle';
}
let shots=[];function projectile(f,o){let dir=f.flip?-1:1;shots.push({x:f.x+dir*45,y:f.y+35,vx:dir*8,life:80,owner:f,other:o,r:12})}
function doHit(f,o,dmg,range){if(Math.abs(f.x-o.x)<range){o.hp=Math.max(0,o.hp-dmg);o.en=Math.min(100,o.en+10);o.stun=10;o.flash=6;f.en=Math.min(100,f.en+8);f.combo++;f.comboT=55;shake=7;score+=dmg}}
function updateShots(){for(let i=shots.length-1;i>=0;i--){let s=shots[i];s.x+=s.vx;s.life--;if(Math.abs(s.x-s.other.x)<45&&Math.abs(s.y-(s.other.y+35))<45){s.other.hp=Math.max(0,s.other.hp-38);s.other.stun=13;s.other.flash=8;s.owner.en=Math.min(100,s.owner.en+12);shake=10;shots.splice(i,1)}else if(s.life<=0)shots.splice(i,1)}}
function drawBg(){let g=X.createLinearGradient(0,0,0,H);g.addColorStop(0,'#141b35');g.addColorStop(1,'#3a1822');X.fillStyle=g;X.fillRect(0,0,W,H);X.fillStyle='#17162a';for(let i=0;i<14;i++){let x=i*110-(time*.25%110),h=80+(i%5)*35;X.beginPath();X.moveTo(x,world.floor());X.lineTo(x+55,world.floor()-h);X.lineTo(x+110,world.floor());X.fill()}X.fillStyle='#252239';X.fillRect(0,world.floor(),W,H-world.floor());X.strokeStyle='#8a4e3d';X.globalAlpha=.35;for(let i=0;i<12;i++){X.beginPath();X.moveTo(i*130,world.floor()+20);X.lineTo(i*130+70,world.floor()+12);X.stroke()}X.globalAlpha=1}
function limb(x1,y1,x2,y2,w){X.lineWidth=w;X.lineCap='round';X.beginPath();X.moveTo(x1,y1);X.lineTo(x2,y2);X.stroke()}
function drawF(f){let s=f.flip?-1:1,cy=f.y+42, bob=f.action==='idle'?Math.sin(time*.12+f.x)*2:0;X.save();X.translate(f.x,f.y+bob);X.scale(s,1);X.strokeStyle=f.flash?'#fff':f.color;X.fillStyle=f.flash?'#fff':f.color;X.shadowBlur=f.action==='blast'?20:0;X.shadowColor='#55ddff';X.lineCap='round';
// original minimal stick fighter silhouette with rhythmic pose
X.lineWidth=10;X.beginPath();X.arc(0,18,18,0,Math.PI*2);X.fill();
X.lineWidth=9;limb(0,38,0,70,9);let armA=0,armB=0,legA=0,legB=0;if(f.action==='punch'){armA=-.25+Math.min(f.frame,10)*.11;armB=.65;legA=.25;legB=-.35}else if(f.action==='kick'){armA=.65;armB=-.55;legA=-.2;legB=-1.25}else if(f.action==='blast'){armA=-.7;armB=-.7;legA=.3;legB=-.3}else if(f.action==='dash'){armA=-.9;armB=.8;legA=-.8;legB=.8}else{armA=Math.sin(time*.15)*.15;armB=-armA;legA=-armA*.8;legB=armA*.8}
limb(0,42,Math.cos(armA)*35,42+Math.sin(armA)*35,8);limb(0,44,Math.cos(armB)*34,44+Math.sin(armB)*34,8);limb(0,69,Math.sin(legA)*28,69+Math.cos(legA)*34,9);limb(0,69,Math.sin(legB)*28,69+Math.cos(legB)*34,9);if(f.action==='blast'){X.fillStyle='#54e8ff';X.beginPath();X.arc(42,42,9+Math.sin(time*.3)*3,0,7);X.fill()}X.restore()}
function drawShots(){for(const s of shots){let gr=X.createRadialGradient(s.x,s.y,2,s.x,s.y,25);gr.addColorStop(0,'#fff');gr.addColorStop(.3,'#6ff');gr.addColorStop(1,'transparent');X.fillStyle=gr;X.beginPath();X.arc(s.x,s.y,25,0,7);X.fill()}}
function bar(x,y,w,h,val,max,flip,label){X.fillStyle='#090910';X.fillRect(x,y,w,h);X.fillStyle=val/max>.35?'#3de0a0':'#ff5b5b';let ww=w*Math.max(0,val/max);if(flip)X.fillRect(x+w-ww,y,ww,h);else X.fillRect(x,y,ww,h);X.strokeStyle='#ddd';X.strokeRect(x,y,w,h);X.fillStyle='#fff';X.font='bold 14px Arial';X.textAlign=flip?'right':'left';X.fillText(label,flip?x+w:x,y-6)}
function hud(){bar(32,28,260,18,player.hp,player.maxhp,false,'NOVA');bar(W-292,28,260,18,enemy.hp,enemy.maxhp,true,'VEX');bar(32,52,160,9,player.en,100,false,'');bar(W-192,52,160,9,enemy.en,100,true,'');X.fillStyle='#fff';X.textAlign='center';X.font='bold 20px Arial';X.fillText('ROUND '+round,W/2,38);if(player.combo>1){X.font='bold 28px Arial';X.fillStyle='#ffcf4d';X.fillText(player.combo+' HIT!',W*.25,100)}}
function menu(){drawBg();X.textAlign='center';X.fillStyle='#fff';X.font='900 52px Arial';X.fillText('STICK WARRIOR',W/2,H*.32);X.fillStyle='#59e6ff';X.font='900 24px Arial';X.fillText('ENERGY CLASH',W/2,H*.39);X.fillStyle='#fff';X.font='18px Arial';X.fillText('Fast 1v1 stick combat • original characters & effects',W/2,H*.46);X.fillStyle='#172034';X.fillRect(W/2-130,H*.55,260,62);X.strokeStyle='#62e9ff';X.strokeRect(W/2-130,H*.55,260,62);X.fillStyle='#fff';X.font='bold 22px Arial';X.fillText('PLAY',W/2,H*.55+40);X.font='14px Arial';X.fillText('Click / Enter',W/2,H*.55+84)}
function over(){drawBg();X.textAlign='center';X.fillStyle='#fff';X.font='900 48px Arial';X.fillText(player.hp>0?'VICTORY':'DEFEAT',W/2,H*.35);X.font='20px Arial';X.fillText('Score: '+score,W/2,H*.43);X.fillStyle='#1b263c';X.fillRect(W/2-130,H*.52,260,60);X.fillStyle='#fff';X.font='bold 20px Arial';X.fillText('PLAY AGAIN',W/2,H*.52+38);X.font='14px Arial';X.fillText('R = restart',W/2,H*.52+86);X.fillStyle='#58e8ff';X.fillText('Watch ad for a bonus revive',W/2,H*.66)}
function loop(){time++;if(shake>0)shake*=.86;X.save();if(shake>1)X.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);if(state==='menu'){menu()}else if(state==='fight'){drawBg();updateF(player,time,enemy,true);updateF(enemy,time,player,false);updateShots();drawShots();drawF(player);drawF(enemy);hud();if(player.hp<=0||enemy.hp<=0){state='over';if(window.PokiSDK)PokiSDK.gameplayStop();setTimeout(ad,250)}}else over();X.restore();requestAnimationFrame(loop)}
addEventListener('pointerdown',e=>{if(state==='menu'){ad();state='fight';if(window.PokiSDK)PokiSDK.gameplayStart()}else if(state==='over'){if(e.clientX>W/2-150&&e.clientX<W/2+150&&e.clientY>H*.5&&e.clientY<H*.65){ad();reset()}}});addEventListener('keydown',e=>{if(e.key.toLowerCase()==='r'&&state==='over'){ad();reset()}if(e.key==='Enter'&&state==='menu'){ad();state='fight';if(window.PokiSDK)PokiSDK.gameplayStart()}if(e.key.toLowerCase()==='q'&&state==='over')reward()});
loop();
