import {fighters,skills} from "./data.js";import {VFX} from "./vfx.js";import {Player} from "./player.js";import {Enemy} from "./enemy.js";import {Renderer} from "./render.js";
const canvas=document.querySelector("#game"),ctx=canvas.getContext("2d"),W=1280,H=720,G=585,vfx=new VFX(ctx),renderer=new Renderer(ctx,vfx);
let selected="kai",mode="lobby",wave=1,score=0,coins=1250,enemies=[],keys={a:false,d:false,jump:false},shake=0;
const player=new Player(vfx,selected);
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
function toast(t){let e=$("#toast");e.textContent=t;e.style.opacity=1;setTimeout(()=>e.style.opacity=0,900)}
function setupRoster(){let box=$("#roster");box.innerHTML="";for(const [id,f] of Object.entries(fighters)){let el=document.createElement("div");el.className="fighter"+(id===selected?" active":"");el.innerHTML=`<div class="avatar">${f.icon}</div><div><b>${f.name}</b><br><small>${id==="kai"?"Cận chiến • tốc độ":"id"}</small></div>`;el.onclick=()=>select(id,el);box.appendChild(el)}select(selected)}
function select(id,el){selected=id;player.hero=id;let f=fighters[id];$("#fighterName").textContent=f.name;$("#power").style.width=f.power+"%";$("#defense").style.width=f.defense+"%";$("#speed").style.width=f.speed+"%";$$(".fighter").forEach(x=>x.classList.remove("active"));if(el)el.classList.add("active")}
function setupSkills(){let box=$("#skills");box.innerHTML=skills.map(s=>`<button class="skill" data-id="${s.id}"><b>${s.icon}</b><small>${s.key}</small><span class="cool"></span></button>`).join("");$$(".skill").forEach(b=>b.onclick=()=>use(b.dataset.id,b))}
function use(id,button){if(mode!=="game")return;button?.classList.add("flash");setTimeout(()=>button?.classList.remove("flash"),180);if(id==="attack")player.pulse(enemies);if(id==="dash")player.flashStep();if(id==="slash")player.crescent(enemies);if(id==="nova")player.nova(enemies);if(id==="meteor"){player.meteor(enemies);shake=20}}
function spawn(){let n=Math.min(3+Math.floor(wave*1.1),11);for(let i=0;i<n;i++)enemies.push(new Enemy(760+i*62,wave%5===0&&i===n-1,wave))}
function enter(){mode="game";$("#lobby").classList.add("hidden");$("#hud").classList.remove("hidden");$("#result").classList.add("hidden");wave=1;score=0;enemies=[];player.hp=100;player.energy=100;player.x=240;spawn();toast("FIGHT!")}
function finish(){mode="result";$("#hud").classList.add("hidden");$("#result").classList.remove("hidden");$("#resultText").textContent=`Wave ${wave} • Score ${score} • ✦ ${coins}`}
function update(){if(mode!=="game")return;player.update(keys,G,()=>{});if(keys.attack){use("attack",document.querySelector('[data-id="attack"]'));keys.attack=false}if(keys.dash){use("dash",document.querySelector('[data-id="dash"]'));keys.dash=false}if(keys.q){use("slash",document.querySelector('[data-id="slash"]'));keys.q=false}if(keys.e){use("nova",document.querySelector('[data-id="nova"]'));keys.e=false}if(keys.r){use("meteor",document.querySelector('[data-id="meteor"]'));keys.r=false}
for(const e of enemies)e.update(player,vfx);enemies=enemies.filter(e=>{if(e.hp<=0){score+=e.elite?600:100;coins+=e.elite?60:10;vfx.burst(e.x,e.y+35,e.elite?"#ff3d6b":"#67e8ff",35,12);return false}return true});if(!enemies.length){wave++;coins+=30;spawn();toast("WAVE "+wave)}if(player.hp<=0)finish();
$("#hp").style.width=Math.max(0,player.hp)+"%";$("#energy").style.width=player.energy+"%";$("#coins").textContent=coins;$("#wave").textContent=wave;let combo=$("#combo");combo.textContent=player.combo>1?player.combo+" HIT":"";combo.classList.toggle("show",player.combo>1);
$$(".skill").forEach(b=>{let id=b.dataset.id,cd=player.cool[id]||0;b.querySelector(".cool").textContent=cd?Math.ceil(cd/60):"";b.classList.toggle("ready",!cd&&(!skills.find(s=>s.id===id)?.cost||player.energy>=skills.find(s=>s.id===id).cost))})}
function draw(){ctx.save();ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);renderer.bg(W,H,G);if(mode==="game"){renderer.stick(player,fighters[selected].accent);renderer.enemies(enemies);vfx.draw()}else vfx.draw();ctx.restore();shake*=.86;vfx.update()}
function loop(){update();draw();requestAnimationFrame(loop)}setupRoster();setupSkills();loop();
addEventListener("keydown",e=>{if(e.code==="KeyA"||e.code==="ArrowLeft")keys.a=true;if(e.code==="KeyD"||e.code==="ArrowRight")keys.d=true;if(e.code==="KeyW"||e.code==="ArrowUp")keys.jump=true;if(e.code==="Space")keys.attack=true;if(e.code==="ShiftLeft"||e.code==="ShiftRight")keys.dash=true;if(e.code==="KeyQ")keys.q=true;if(e.code==="KeyE")keys.e=true;if(e.code==="KeyR")keys.r=true;if(["Space","ArrowLeft","ArrowRight","ArrowUp"].includes(e.code))e.preventDefault()});
addEventListener("keyup",e=>{if(e.code==="KeyA"||e.code==="ArrowLeft")keys.a=false;if(e.code==="KeyD"||e.code==="ArrowRight")keys.d=false});
$("#playBtn").onclick=enter;$("#dailyBtn").onclick=()=>{coins+=250;$("#lobbyCoins").textContent=coins;toast("+250 ✦")};$("#lobbyBtn").onclick=()=>{mode="lobby";$("#result").classList.add("hidden");$("#lobby").classList.remove("hidden");$("#lobbyCoins").textContent=coins};$("#reviveBtn").onclick=()=>{player.hp=100;player.energy=100;mode="game";$("#result").classList.add("hidden");$("#hud").classList.remove("hidden");toast("REVIVED!")};
$("#lobbyCoins").textContent=coins;
