export class Player{
 constructor(vfx,hero){this.vfx=vfx;this.hero=hero;this.x=240;this.y=495;this.vx=0;this.vy=0;this.face=1;this.hp=100;this.energy=100;this.inv=0;this.combo=0;this.comboTimer=0;this.attackTimer=0;this.anim=0;this.cool={slash:0,nova:0,meteor:0}}
 update(keys,ground,attack){this.anim++;if(keys.a)this.vx-=.65;if(keys.d)this.vx+=.65;if(keys.a)this.face=-1;if(keys.d)this.face=1;this.vx*=.86;this.vx=Math.max(-7,Math.min(7,this.vx));if(keys.jump&&this.y>=ground-91){this.vy=-14;keys.jump=false}this.vy+=.68;this.y+=this.vy;if(this.y>ground-91){this.y=ground-91;this.vy=0}this.x+=this.vx;this.x=Math.max(55,Math.min(1225,this.x));this.energy=Math.min(100,this.energy+.1);this.inv=Math.max(0,this.inv-1);this.attackTimer=Math.max(0,this.attackTimer-1);this.comboTimer--;if(this.comboTimer<=0)this.combo=0;for(let k in this.cool)this.cool[k]=Math.max(0,this.cool[k]-1)}
 hit(d){if(this.inv)return false;this.hp-=d;this.inv=10;this.vfx.burst(this.x,this.y+45,"#ff4568",10,7);return true}
 pulse(enemies){this.attackTimer=10;this.combo=Math.min(9,this.combo+1);this.comboTimer=48;this.vfx.slash(this.x+this.face*50,this.y+40,this.face,"#b5f6ff");for(const e of enemies)if(Math.abs(e.x-this.x)<115)this.damage(e,15+this.combo*3)}
 damage(e,d){e.hp-=d;e.vx+=this.face*5;this.vfx.burst(e.x,e.y+35,this.hero==="rei"?"#ff713e":"#6ee7ff",8,7)}
 flashStep(){if(this.energy<12)return;this.energy-=12;this.inv=18;this.vx=this.face*19;this.vfx.trail(this.x,this.y+55,"#8b5cf6");this.vfx.burst(this.x,this.y+50,"#8b5cf6",18,9)}
 crescent(enemies){if(this.cool.slash||this.energy<22)return;this.energy-=22;this.cool.slash=75;this.combo=Math.min(9,this.combo+2);this.comboTimer=60;this.vfx.slash(this.x+this.face*50,this.y+35,this.face,"#67e8ff",true);for(const e of enemies)if(Math.abs(e.x-this.x)<240)this.damage(e,42+this.combo*3)}
 nova(enemies){if(this.cool.nova||this.energy<40)return;this.energy-=40;this.cool.nova=150;this.vfx.ring(this.x,this.y+45,"#a78bfa",40);this.vfx.burst(this.x,this.y+45,"#a78bfa",60,11);for(const e of enemies)if(Math.abs(e.x-this.x)<330)this.damage(e,58)}
 meteor(enemies){if(this.cool.meteor||this.energy<68)return;this.energy-=68;this.cool.meteor=270;this.vfx.burst(this.x,this.y+40,"#f0abfc",100,14);for(const e of enemies)this.damage(e,88);}}
