import{FIGHTERS,SKILLS}from"./data/config.js";import{load,save,daily}from"./core/save.js";import{Poki}from"./core/poki.js";import{Input}from"./core/input.js";import{Camera}from"./systems/camera.js";import{VFX}from"./systems/vfx.js";import{Combat}from"./systems/combat.js";import{World}from"./systems/world.js";import{Player}from"./entities/player.js";import{Renderer}from"./systems/renderer.js";import{UI}from"./ui/ui.js";
const $=s=>document.querySelector(s),canvas=$("#game"),ctx=canvas.getContext("2d"),saveData=load(),input=new Input(),cam=new Camera(),vfx=new VFX(),combat=new Combat(vfx,cam),worldRenderer=new Renderer(),ui=new UI();let mode="boot",player,world,last=performance.now(),selected=saveData.selected||"kai";
function renderFighters(){let box=$("#fighters");box.innerHTML="";for(let [id,f] of Object.entries(FIGHTERS)){let d=document.createElement("div");d.className="fighterItem";d.dataset.id=id;d.innerHTML=`<div class="avatar">${f.icon}</div><div><b>${f.name}</b><br><small>PRO FIGHTER</small></div>`;d.onclick=()=>{selected=id;saveData.selected=id;save(saveData);ui.fighter(id,f)};box.appendChild(d)}ui.fighter(selected,FIGHTERS[selected])}
function renderSkills(){let box=document.createElement("div");box.className="skillbar";box.id="skillbar";box.innerHTML=SKILLS.map(s=>`<button class="skill" data-id="${s.id}"><b>${s.icon}</b><small>${s.key}</small><span class="cool"></span></button>`).join("");$("#hud").appendChild(box);box.querySelectorAll(".skill").forEach(b=>b.onclick=()=>skill(b.dataset.id))}
function skill(id){if(mode!=="game")return;let ok=false;if(id==="m1")player.m1(world.enemies),ok=true;if(id==="dash")player.dash();if(id==="crescent")player.crescent(world.enemies);if(id==="nova")player.nova(world.enemies);if(id==="breaker")player.breaker(world.enemies)}
async function start(){Poki.stop();$("#ad").classList.remove("hidden");await Poki.ad();$("#ad").classList.add("hidden");mode="game";$("#lobby").classList.add("hidden");$("#result").classList.add("hidden");$("#hud").classList.remove("hidden");player=new Player(vfx,combat,FIGHTERS[selected]);world=new World(vfx,combat);Poki.start();ui.toast("FIGHT!")}
async function revive(){Poki.stop();$("#ad").classList.remove("hidden");let ok=await Poki.reward();$("#ad").classList.add("hidden");if(ok){player.hp=100;player.energy=100;player.inv=90;mode="game";$("#result").classList.add("hidden");$("#hud").classList.remove("hidden");Poki.start();ui.toast("REVIVED")}}
function lose(){mode="result";Poki.stop();$("#hud").classList.add("hidden");$("#result").classList.remove("hidden");$("#resultText").textContent=`Wave ${world.wave} • Score ${world.score}`;saveData.best=Math.max(saveData.best,world.wave);saveData.coins+=Math.floor(world.score/100);save(saveData);ui.coins(saveData.coins)}
function pause(){if(mode==="game"){mode="pause";Poki.stop();$("#pausePanel").classList.remove("hidden")}else if(mode==="pause"){mode="game";$("#pausePanel").classList.add("hidden");Poki.start()}}
function update(){if(mode!=="game")return;if(combat.tick())return;player.update(input,world.enemies);if(input.consume("attack"))skill("m1");if(input.consume("dash"))skill("dash");if(input.consume("q"))skill("crescent");if(input.consume("e"))skill("nova");if(input.consume("r"))skill("breaker");if(world.update(player)){saveData.coins+=30;save(saveData);ui.coins(saveData.coins);ui.toast("WAVE "+world.wave)}if(player.hp<=0)lose();ui.hud(player,world)}
function draw(t){ctx.clearRect(0,0,1280,720);worldRenderer.bg(ctx,t);if(player&&world){cam.follow(player);cam.begin(ctx);worldRenderer.draw(ctx,player,world.enemies,FIGHTERS[selected]);vfx.draw(ctx);cam.end(ctx)}vfx.update()}
function loop(t){update();draw(t);requestAnimationFrame(loop)}
$("#play").onclick=start;$("#daily").onclick=()=>{if(daily(saveData)){ui.coins(saveData.coins);ui.toast("+250 DAILY")}else ui.toast("DAILY CLAIMED")};$("#pause").onclick=pause;$("#resume").onclick=pause;$("#toLobby").onclick=()=>{mode="lobby";$("#pausePanel").classList.add("hidden");$("#hud").classList.add("hidden");$("#lobby").classList.remove("hidden")};$("#revive").onclick=revive;$("#retry").onclick=start;$("#resultLobby").onclick=()=>{mode="lobby";$("#result").classList.add("hidden");$("#lobby").classList.remove("hidden")};
(async()=>{for(let i=0;i<=100;i+=5){$("#loader").style.width=i+"%";await new Promise(r=>setTimeout(r,10))}await Poki.init();Poki.load();renderFighters();renderSkills();ui.coins(saveData.coins);$("#boot").classList.add("hidden");$("#lobby").classList.remove("hidden");mode="lobby";loop(performance.now())})();